# Generated by Django 6.0.3 on 2026-04-03 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_follow_friendrequest_friendship'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='follow',
            new_name='users_follo_followe_229ec1_idx',
            old_name='users_follo_follower_6417dd_idx',
        ),
        migrations.RenameIndex(
            model_name='follow',
            new_name='users_follo_followi_dcf251_idx',
            old_name='users_follo_following_191f0f_idx',
        ),
        migrations.RenameIndex(
            model_name='friendrequest',
            new_name='users_frien_receive_33fa3d_idx',
            old_name='users_frie_receiver_73e9a9_idx',
        ),
        migrations.RenameIndex(
            model_name='friendship',
            new_name='users_frien_user1_i_089e47_idx',
            old_name='users_frie_user1_8dcd7d_idx',
        ),
        migrations.RenameIndex(
            model_name='friendship',
            new_name='users_frien_user2_i_cf6d20_idx',
            old_name='users_frie_user2_3d6a04_idx',
        ),
    ]
