# Generated by Django 6.0.3 on 2026-04-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_post_content_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('haha', 'Haha')], db_index=True, default='like', max_length=10),
        ),
        migrations.AddField(
            model_name='postlike',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('haha', 'Haha')], db_index=True, default='like', max_length=10),
        ),
    ]
